version: 1.0.{build}
image: Visual Studio 2017
configuration: Release
install:
- ps: >-
    cd src
    
    dotnet restore

build:
  project: src/SharpShaderCompiler.sln
  verbosity: minimal

artifacts:
- path: src\SharpShaderCompiler\bin\Release\*.nupkg
  name: SharpShaderCompiler Nuget

deploy:
  provider: NuGet
  server: https://www.myget.org/F/feliwir/api/v2/package
  api_key:
    secure: weRKCN6uh+JEb70fPUrGkOgcSyzkeoXydxHiqcPuZj+kP60lJ+c0MV9hcGCP+s0u
  on:
    branch: master